name: CMake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y cmake g++

    - name: Configure project
      run: cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install

    - name: Build project
      run: cmake --build _build

    - name: Install project
      run: cmake --build _build --target install
